export { PasswordInput } from '@components/form/FormItem/passwd'
export { ValidateCode } from '@components/form/FormItem/validateCode'
export { Input } from '@components/form/FormItem/input'
export { NormalPicker } from '@components/form/FormItem/picker'
export { ApplyButton } from '@components/form/FormItem/applyButton'
export { NormalDatePicker as DatePicker } from '@components/form/FormItem/datePicker'
export { RadioInput } from '@components/form/FormItem/radioInput'
export { PhonePicker } from '@components/form/FormItem/phonePicker'
export { PhotoPicker } from '@components/form/FormItem/photoPicker'
export { HandPhotoPicker } from '@components/form/FormItem/handPhotoPicker'
export { IdcardPhotoPicker } from '@components/form/FormItem/idcardPhotoPicker'
