export { PasswordInput } from '@components/form/FormItem/passwd'
export { ValidateCode } from '@components/form/FormItem/validateCode'
export { Input } from '@components/form/FormItem/input'
export { NormalPicker } from '@components/form/FormItem/picker'
export { ApplyButton } from '@components/form/FormItem/applyButton'
