export { PasswordInput } from '@components/form/passwd'
export { ValidateCode } from '@components/form/validateCode'
export { Input } from '@components/form/input'
export { MaskInput } from '@components/form/maskInput'
export { NormalPicker } from '@components/form/picker'
export { ApplyButton } from '@components/form/applyButton'
export { NormalDatePicker as DatePicker } from '@components/form/datePicker'
export { RadioInput } from '@components/form/radioInput'
export { PhonePicker } from '@components/form/phonePicker'
export { LivenessPicker } from '@components/form/Liveness'
export { PhotoPicker } from '@components/form/photoPicker'
