export const REGEX_PASSWORD = new RegExp('^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{6,12}$')
export const REGEX_PHONE = new RegExp('^[1-9][0-9]{9}$')
export const REGEX_COMPANYPHONE = new RegExp('^[0-9]{1,20}$')
export const REGEX_BANK_CARD = new RegExp('^\\d{18}$')
export const REGEX_BANK_CLABE = new RegExp('^\\d{16}$')
export const REGEX_VALIDATE_CODE = new RegExp('^\\d{4}$')
