import StyleSheet from 'react-native-adaptive-stylesheet'
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#CCECDB',
  },
  bannerContainer: {
    height: 226,
    position: 'relative',
  },
  bannerText: {
    fontSize: 19,
    color: '#333230',
    fontFamily: 'ArialRoundedMTBold',
    position: 'absolute',
    width: 140,
    height: 56,
    left: 19.5,
    top: 44.5,
    zIndex: 999,
  },
  bannerImg: {
    height: 226,
    width: 375,
  },
  loanContainer: {
    marginHorizontal: 10,
    backgroundColor: '#F8F8F8',
    borderRadius: 5,
    paddingHorizontal: 15,
    paddingTop: 17,
    paddingBottom: 22.5,
  },
  loanTitle: {
    fontFamily: 'ArialRoundedMTBold',
    fontSize: 18,
    color: '#333230',
  },
  loanInfo: {
    flex: 1,
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingTop: 16.5,
    paddingBottom: 19.5,
    alignItems: 'center',
  },
  loanInfoLeft: {
    color: '#7B7B7B',
    fontSize: 12,
    fontFamily: 'ArialRoundedMTBold',
  },
  loanInfoRight: {
    color: '#00A24D',
    fontSize: 25,
    fontFamily: 'ArialRoundedMTBold',
  },
  loanSliderContainer: {},
  loanHint: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'relative',
    paddingBottom: 60,
  },
  loanHintWarnContainer: {
    position: 'absolute',
    top: 12,
    width: 325,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  loanHintWarn: {
    backgroundColor: 'rgba(255, 168, 98, 1)',
    paddingTop: 7,
    paddingBottom: 8,
    paddingHorizontal: 10,
    borderRadius: 8.5,
    textAlign: 'center',
    width: 278,
  },
  loanHintWarnText: {
    color: '#ffffff',
    fontSize: 11,
    fontFamily: 'ArialRoundedMTBold',
  },
  loanHintText: {
    color: '#00A24D',
    fontSize: 11,
    fontFamily: 'ArialRoundedMTBold',
  },
  line: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  line2: {
    marginTop: 10,
  },
  lineLeft: {
    color: '#7F7F7F',
    fontSize: 12,
  },
  lineRight: {
    color: '#FF8010',
    fontSize: 14,
  },
  track: {
    height: 12,
    borderRadius: 6,
    backgroundColor: '#C4CCC2',
  },
  thumb: {
    width: 80,
    borderRadius: 8,
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.5,
    shadowRadius: 19,
    backgroundColor: '#FFD454',
  },
  innerSlot: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 3,
    flex: 1,
    height: 24,
  },
  innerText: {
    color: '#302F2B',
    fontSize: 14,
    fontFamily: 'ArialRoundedMTBold',
  },
  innerImg: {
    width: 6,
    height: 10,
  },
  btnWrap: {
    paddingHorizontal: 25,
  },
  companyWrap: {
    paddingHorizontal: 28.5,
    paddingVertical: 10,
  },
  companyText: {
    fontSize: 15,
    color: '#1A1A1A',
    fontFamily: 'Metropolis',
    textAlign: 'center',
    lineHeight: 24,
  },
  agreementWrap: {
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  agreementText: {
    color: '#1A1A1A',
    fontFamily: 'Metropolis',
  },
  agreementTextImg: {
    color: '#00A24D',
    fontFamily: 'ArialRoundedMTBold',
  },
  agreementTextWarn: {
    color: 'red',
    fontFamily: 'Metropolis',
    fontSize: 11,
  },
  slidesWrap: {
    paddingBottom: 17,
    paddingHorizontal: 23,
  },
  slidesTitleWrap: {
    paddingHorizontal: 7,
    paddingVertical: 27.5,
  },
  slidesTitle: {
    fontFamily: 'ArialRoundedMTBold',
    color: '#333230',
    fontSize: 18,
  },
  dot: {
    backgroundColor: '#7B7B7B',
    width: 4,
    height: 4,
    borderRadius: 2,
    marginHorizontal: 4,
    zIndex: 998,
    marginBottom: 25,
  },
  activeDot: {
    backgroundColor: '#00A24D',
    width: 7,
  },
  swiperWrap: {
    width: 325,
    height: 234,
    backgroundColor: '#ffffff',
    position: 'relative',
    paddingTop: 20,
    paddingLeft: 11.5,
    paddingBottom: 15,
    // marginHorizontal: 14,
    borderRadius: 5,
  },
  swiperImg: {
    position: 'absolute',
    top: 0,
    right: 0,
  },
  swiperImg1: {
    width: 142.5,
    height: 179,
  },
  swiperImg2: {
    top: 36,
    width: 131.5,
    height: 175.5,
  },
  swiperImg3: {
    width: 162.5,
    height: 195.5,
  },
  swiperTextIndexWrap: {
    marginLeft: 5,
    width: 33,
    height: 33,
    borderRadius: 16.5,
    backgroundColor: '#00A24D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  swiperTextIndex: {
    color: '#ffffff',
    fontFamily: 'ArialRoundedMTBold',
    fontSize: 18,
  },
  swiperTextTitle: {
    paddingTop: 21,
    fontFamily: 'ArialRoundedMTBold',
    paddingBottom: 16.5,
    color: '#00A24D',
    fontSize: 16,
  },
  swiperTextSubtitle: {
    width: 160,
    color: '#7B7B7B',
    fontSize: 16,
    fontFamily: 'Metropolis',
  },
  carouselWrap: {
    height: 40,
    backgroundColor: '#FFECB0',
    paddingHorizontal: 23,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselImgWrap: {
    position: 'relative',
    marginRight: 8.5,
    width: 22,
    height: 18,
  },
  carouselImg: {
    position: 'absolute',
  },
  carouselContentTextWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselContentText: {
    fontFamily: 'Metropolis',
    fontSize: 11,
  },
  fakeBanner: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16.5,
    justifyContent: 'space-between',
    paddingTop: 28.5,
    paddingBottom: 21,
    borderRadius: 5,
  },
  fakeBannerTitle: {
    fontFamily: 'ArialRoundedMTBold',
    color: '#333230',
    fontSize: 18,
    textAlign: 'center',
    paddingBottom: 15,
  },
  fakeBannerAmountTitle: {
    fontFamily: 'ArialRoundedMTBold',
    color: '#333230',
    fontSize: 36,
    textAlign: 'center',
    paddingBottom: 12,
  },
  fakeBannerAmountUnit: {
    fontSize: 30,
  },
})
